# Generated by Django 6.0.1 on 2026-02-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='detail_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='short_description',
            field=models.TextField(),
        ),
    ]
